### ISSUE TITLE
Capsule lengths

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#107]
The generic definition of Capsule includes the `Capsule Length` field that is the length of all remaining fields, which depends on the type. We state that the length can be zero.

However, many of the capsule types we define cannot be zero-length:

* REGISTER_DATAGRAM - at least 1 byte
* REGISTER_DATAGRAM_CONTEXT - at least 2 bytes
* Datagram Close - at least 2 bytes

We could be more prescriptive of these capsules. Such as explicitly marking the minimal length in the figures, or noting it in the prose. We might also recommend that receivers of these capsules reject capsules that are clearly too short

**Comment by DavidSchinazi** [comment]
How about we do something similar to [this generic text about h3 frames](https://datatracker.ietf.org/doc/html/draft-ietf-quic-http#section-7.1):

> Each frame's payload MUST contain exactly the fields identified in its description. A frame payload that contains additional bytes after the identified fields or a frame payload that terminates before the end of the identified fields MUST be treated as a connection error of type H3_FRAME_ERROR; see Section 8. In particular, redundant length encodings MUST be verified to be self-consistent; see Section 10.8.

**Comment by afrind** [comment]
Is it also a connection error / FRAME_ERROR if the stream containing capsules ends in the middle of a capsule?

**Comment by LPardue** [comment]
Since capsules are above the layer of H2 and H3, closing a connection seems quite extreme.

I would treat these a bit like truncated HTTP content. Terminating the data stream seems like a decent recommendation,

**Comment by afrind** [comment]
> Capsules are end-to-end so if the stream is aborted mid-capsule by an endpoint, there's not much an intermediary can do, and it shouldn't impact other streams on the same connection. 

If an endpoint aborts a stream mid-capsule, it should do so with a RST and not a FIN, right? The text in H3 (right below your linked text) talks about truncation on graceful completion.

Also, is the recommendation from the original issue (malformed frames) also be a stream or a connection error?  It seems like we should be applying the same logic to the two cases, right?

**Comment by LPardue** [comment]
Capsules aren't frames. We should expect some implementations to allow applications to inject their own capsules, just like application can insert HTTP content today. There might be valid reasons to terminate a stream, such as the user losing interest in a tunnelled connection, an implementation that is taking opaque application data and sending it has no way to ensure it doesn't send a truncated capsule.

For these reasons, I think recommending a connection closure is too extreme (endpoints can always do that if they really want to). Recommending a stream closure, with possibly a new error code, seems right.
