### ISSUE TITLE
RELIABLE_DATAGRAM

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-masque/draft-ietf-masque-h3-datagram#111]
We should revisit [the RELIABLE_DATAGRAM question](https://mailarchive.ietf.org/arch/msg/masque/JImas3YR45txq60pZR2Ab-_LxzQ/).

**Comment by martinthomson** [comment]
A discussion of this has broken out [here](https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/pull/124#discussion_r751879354).

My understanding is that there are two major motivating reasons for this:

1. The desire for end-to-end finite-sized message.  I think we resolved that capsules *of any type* provide this capability, so any attempt to add the capability to this draft is largely based on the desire to have a singular form.

2. Something about [zero-latency extensibility](https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/pull/124#discussion_r753423751).

The latter is the interesting one. I admit that I don't understand it well, especially the part that uses a RELIABLE_DATAGRAM capsule.

The desire to be able to negotiate different uses for QUIC DATAGRAM frames *and* for clients to be able to exercise those options prior to seeing any response from a server is very much context-specific.  Lowering latency is interesting, but I don't have a clear path from that requirement to this proposed mechanism.

Low-latency extensibility for DATAGRAM frames is something that can be enabled for each protocol by defining a "usage" field in the DATAGRAM payload for that protocol. The goal here seems to be to be able to impose the use of this "usage" field on any protocol, even if that protocol didn't originally choose to allow that.

That's quite a narrow applicability:

* uses DATAGRAM frames (unreliable, finite sized messages)
* has multiple uses for those DATAGRAM frames
* has some potential uses that are unknown at the time the protocol is defined (that naturally flows from the multiple uses scenario)
* wants clients to be able to send DATAGRAM frames immediately (which might well be a generic capability)
* didn't want the overhead of an additional field in DATAGRAM frames in the original design

It seems like this imposes a constraint on a client that wants to exercise this extensibility. Such a client can't send DATAGRAM frames immediately.  It has to use RELIABLE_DATAGRAM until the negotiation is complete.  That seems like an undesirable property to me, but I can see some advantages to it.  It's also unclear whether a server is similarly constrained.  It might answer a request without knowing that the client wants to support this extension, so it might also need to refrain from sending DATAGRAM frames until can perform the same negotiation.

The simpler design alternative is to add a "usage" tag to every DATAGRAM for all protocols.  That's easy: unknown (or unnegotiated) usage labels are ignored.  But that's overhead and I'm opposed to that.  It says that someone defining a protocol can't know what they are doing (which shows a great lack of faith, even if experience suggests that we often get this sort of thing wrong).

No matter what path I plot, I can't see a path in which RELIABLE_DATAGRAM is useful.

@DavidSchinazi, perhaps you can help us understand your vision better.  That said, co-opting this issue might not be the right way to do that; what you are talking about might be solved using other mechanisms.  Perhaps we should discuss the low-latency extensibility requirement in its own issue.

**Comment by afrind** [comment]
> Low-latency extensibility for DATAGRAM frames is something that can be enabled for each protocol by defining a "usage" field in the DATAGRAM payload for that protocol.

So much this.  I don't know if I'd call it usage, but I think any protocol that wants DATAGRAM extensibility should be using a varint at the beginning of the payload to facilitate it.

> The simpler design alternative is to add a "usage" tag to every DATAGRAM for all protocols. ... But that's overhead and I'm opposed to that. 

Not all protocols need it.  WebTransport doesn't (yet anyways).  I don't think we should require it in H3 Datagram.  To refine the point about overhead though, I am OK with this overhead in CONNECT-UDP/CONNECT-IP if those protocols want extensibility.  The < 0.1% overhead there seems like a reasonable tradeoff.

> No matter what path I plot, I can't see a path in which RELIABLE_DATAGRAM is useful.

Given that I think there are better patterns for extensibility at higher layers, I don't think RELIABLE_DATAGRAM is useful at this layer.

**Comment by DavidSchinazi** [comment]
I've filed #125 to discuss zero-latency extensibility, since RELIABLE_DATAGRAM is one potential solution but not the only possible one.

**Comment by DavidSchinazi** [comment]
Ben and I discussed this today, and came to the conclusion that, now that we've merged the result of the design team, there is no need for this in the base HTTP Datagrams document and it can be implemented by a future extension. So I'm closing this issue with no action. Please comment/reopen if you disagree.
