### ISSUE TITLE
Serialization over HTTP/1.x of multiple HTTP requests with Datagram

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-h3-datagram#120]
In Section 2:

When running over HTTP/1, requests are strictly serialized in the connection, therefore the first layer of demultiplexing is not needed.

Is there any actual possibility to run more than a single request with HTTP datagram support over an transport connection? When one runs an HTTP request that enables datagram I don't see how it would be possible to close that request in any other way than closing the underlying transport connection. Or are there a way that I am missing that would enable one to close this request, and then issue another pipelined HTTP request that also uses HTTP datagrams? 

Is there a need to clarify this, or make it clear that only a single HTTP request with datagram can be sent?

**Comment by LPardue** [comment]
In section 2, we've yet to mention anything about how the rest of the spec operates. So the comment in isolation is correct when talking about the general concept of multiplexin.

I see your point but I'm not sure saying anything more here will help. Section 4.1 provides the details that implementers need to do the right thing.

**Comment by gloinul** [comment]
Okay, but lets include Section 4.1 also into this. I assume you are referring to this sentence:

In HTTP/1.x, the data stream consists of all bytes on the connection that follow the blank line that concludes either the request header section, or the 2xx (Successful) response header section.

But, per https://www.ietf.org/archive/id/draft-ietf-httpbis-messaging-19.html#name-message-body-length this body length length rules will be those that could govern a closure of a HTTP request enabling datagram. Would it be realistic to actually make it clear that if one enable HTTP Datagram transport close is the only, way or is that just creating additional rules making implementation even more? Otherwise do we need additional analysis if there are possibility that any of these rules could actually result in a closing a HTTP request?

**Comment by LPardue** [comment]
There is no HTTP content on upgrade requests, we should link to the definition of Upgrade  https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.7.8 and make things slightly more clear in Section 4.1.

**Comment by gloinul** [comment]
Ok, I guess it becomes a question of which method for enabling datagram one uses, if this is an upgrade or a new method. And I would note that Connect method appears to have some interesting exceptions compared to other methods. Which I think makes this into a requirement on the using method/upgrade that uses HTTP datagrams to actually specify this aspect.

**Comment by DavidSchinazi** [comment]
I've written up #122 to clarify that pipelining is not supported.
