### ISSUE TITLE
Zero-Latency Extensibility

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-h3-datagram#125]
We've been discussing this topic on the [design team PR](https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/pull/124#discussion_r751879354) and on the [RELIABLE_DATAGRAM issue](https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/issues/111), but @martinthomson rightly points out that this deserves its own issue.

# Motivation

There is interest in deploying extensions to protocols that use HTTP Datagrams. Some of these extensions require the ability to send multiple types of HTTP datagrams associated with a single request stream. For example,
* an extension to CONNECT-UDP that allows measuring the HTTP Datagram MTU
* an extension to CONNECT-IP that allows compressing IP headers

This means that when these extensions are in use, HTTP Datagrams carry an identifier that allows the receiver to know what kind of HTTP Datagram it's receiving (e.g. "is this a UDP payload or an MTU probe?" or "is this a full IP packet or a compressed one?").

One potential solution is to have CONNECT-UDP and CONNECT-IP require their HTTP Datagrams to always start with an identifier. This has the unfortunate downside of wasting a byte for requests that do not use extensions, and also precludes WebTransport from using extensions in the future.

Alternatively,  we could define an optional extension to HTTP Datagrams which has the advantage of not wasting bytes when not in use, and allows any protocol relying on HTTP Datagrams to use it if chooses to at any point in the future. This extension would be negotiated via an HTTP header.

# Requirement: Zero-Latency Extensibility

Let's assume we are going with the model of an optional extension to HTTP Datagrams. Since this is optional, a client will not know whether it is supported by the server until it receives the response headers. "Zero-Latency Extensibility" is the ability for a client to send HTTP Datagrams (both the "regular" datagram that's the default one from the request, and the "extension" datagrams). Note that this doesn't apply to the server because the server doesn't send HTTP Datagrams until after it's parsed the request headers. Let's call the flight of frames and/or packets that go alongside the HTTP request headers the "first flight". The requirement is for the client to be able to send both "regular" and "extension" HTTP datagrams with its first flight, and to have the server parse them as follows: if the server supports the extension, the server can correctly parse both "regular" and "extension" HTTP datagrams from the first flight; if the server doesn't support the extension, the server can correctly parse the "regular" datagrams and drop the "extension" ones.

# Requirement: Unmodified Intermediaries

Intermediaries shouldn't have to know or care about this extension. All that intermediaries need to do is blindly convert between QUIC DATAGRAM frames and DATAGRAM capsules regardless of any extension being used. This puts one constraint on the solution: QUIC DATAGRAM frames and DATAGRAM capsules need to have the same semantics because they can get converted between one another by intermediaries.

# Solution

Solving this problem once the headers is exchanged is pretty straightforward: if both endpoints support the extension, then datagrams start with an identifier. Otherwise, they don't contain the identifier. Getting this to work before the response headers are received is slightly more tricky: it requires having a way to distinguish between datagrams sent before the headers were received and ones sent after. The simplest way to distinguish them is to define two capsules and use the capsule type to tell us which is which.

The datagram context extension works as follows: it is negotiated by adding a header to both request and response, and when both endpoints support it, it adds a context ID varint at the start of the HTTP Datagram Payload field.

Now, in order to achieve zero-latency extensibility, the client needs to be able to send datagrams before receiving the server headers in such a way that the server can correctly parse them (if you add the context ID and the server doesn't support the extension, you don't want the server to parse the context ID as part of the payload).

So here's my idea for how to accomplish that. The extension says the following:
- clients that support the extension are not allowed to send QUIC DATAGRAM frames nor DATAGRAM capsule before they've received the server headers
- the extension defines a new RELIABLE_DATAGRAM_EXT capsule that can be sent before and after receiving server headers
```
Extended Reliable Datagram Capsule {
  Type (i) = RELIABLE_DATAGRAM_EXT,
  Length (i),
  Context ID (i),
  HTTP Datagram Payload (..),
}
```
- the extension does not change the semantics of the RELIABLE_DATAGRAM capsule, that still does not contain a Context ID
```
Reliable Datagram Capsule {
  Type (i) = RELIABLE_DATAGRAM,
  Length (i),
  HTTP Datagram Payload (..),
}
```
- when both endpoints support the extension (after receiving headers) the extension changes the semantics of both the QUIC DATAGRAM frame and DATAGRAM capsule to include a Context ID at the start:
```
Datagram Capsule {
  Type (i) = DATAGRAM,
  Length (i),
  Context ID (i),
  HTTP Datagram Payload (..),
}
HTTP/3 Datagram { // contents of QUIC DATAGRAM frame
  Quarter Stream ID (i),
  Context ID (i),
  HTTP Datagram Payload (..),
}
```
- if the client wishes to use zero-latency extensibility, it can send RELIABLE_DATAGRAM and RELIABLE_DATAGRAM_EXT before receiving the server headers. Both of these will be parsed correctly by servers, whether or not the server supports the extension.

All of this relies on the fact that there is one bit that differentiates the DATAGRAM capsule from the RELIABLE_DATAGRAM capsule (the bit is in the capsule type), so that the extension can give the two capsules different semantics in a way that is backwards compatible.

I'm realizing that calling this RELIABLE_DATAGRAM tied zero-latency extensibility to #111. This would work just as well if we renamed RELIABLE_DATAGRAM to EARLY_DATAGRAM or UNEXTENDED_DATAGRAM.

**Comment by afrind** [comment]
> One potential solution is to have CONNECT-UDP and CONNECT-IP require their HTTP Datagrams to always start with an identifier. This has the unfortunate downside of wasting a byte for requests that do not use extensions

I don't view it as waste.  I view it as the (extremely low) cost of simple and performant 0-RTT extensibility.  When you make mechanisms complex, the may solve problems on paper, but no one will use them -- see HTTP/2 Priorities.  Is there a more concrete argument for how this byte will cause performance problems for users of unextended CONNECT-UDP or CONNECT-IP? 

> and also precludes WebTransport from using extensions in the future.

If WebTransport might ever want to change the layout of H3 Datagrams, it should add an identifier now.

**Comment by martinthomson** [comment]
Yeah, I'm with Alan on this.  This design is considerably more complex and forces clients into using reliable, ordered transfer for ~1RTT if they want to use extensibility.  Spending the byte or so on a type discriminator is far simpler.

For WebTransport, I doubt we'll need this.  We hand off responsibility for the content of datagrams to applications.  And then there is always the possibility of a WebTransport version 2.  (Here, I am forced to acknowledge that protocol negotiation with extended CONNECT is likely a complete disaster, but now we're far enough into speculative territory that I'm OK with that risk.)

**Comment by martinthomson** [comment]
Separately,

> Note that this doesn't apply to the server because the server doesn't send HTTP Datagrams until after it's parsed the request headers.

That presumes that the negotiation of extensions that modify the payload of datagrams occurs atomically.  If the extension is not negotiated atomically and uses capsules that are sent after the request, then a server might process a request and send DATAGRAM frames ignorant of the potential for extensions to be used.  That creates an ambiguity at the client.  The client cannot know if the server has not understood the extension (so that the datagram doesn't include a context/type/usage field) or whether it is using the extension (so that it does) when it receives the first DATAGRAM frame, which is likely to arrive before any negotiation signals.  That means that the server also has to follow the pattern of sending datagrams as part of the stream, with the various markings you have, unless you bind the processing of extensions into the HTTP request header fields.  

There's no mention of how these extensions are negotiated here, so I assume that you are planning to use HTTP header fields in order to get this.  My thought would be that it is easier to do that sort of negotiation with capsules, which is what previous versions of the draft did.

That this comes with this constraint on how extensions are negotiated or used makes it less appealing.

**Comment by DavidSchinazi** [comment]
@martinthomson sorry for being unclear. Whether or not contexts are in use (by which I mean "does the payload start with a context ID varint?")  is negotiated via an HTTP header. That occurs atomically. Subsequently, capsules are used to assign semantics to a given context. There's no ambiguity on the receiver there, because if you receive a datagram for context 4 and you haven't received or understood what context 4 means you can just drop that datagram.

**Comment by tfpauly** [comment]
I agree that it's much simpler to just always have the context ID be present for protocol that want to be able to tag different datagrams. This means there's no complexity about when unreliable datagrams are allowed to be sent, or dealing with headers to try to guess how to interpret payloads. It's much more deterministic and will be less prone to implementation bugs.

**Comment by afrind** [comment]
Since both David and Tommy specifically mentioned "Context ID", I'll point out that the identifier could be the context ID as currently specified in the drafts, but alternate designs are possible.
