### ISSUE TITLE
Do not allow capsules for new methods

### ISSUE THREAD

**Issue by MikeBishop** [ietf-wg-masque/draft-ietf-masque-h3-datagram#129]
The spec currently says:

> This specification defines the "data stream" of an HTTP request as the bidirectional stream of bytes that follow the headers in both directions. In HTTP/1.x, the data stream consists of all bytes on the connection that follow the blank line that concludes either the request header section, or the 2xx (Successful) response header section. In HTTP/2 and HTTP/3, the data stream of a given HTTP request consists of all bytes sent in DATA frames with the corresponding stream ID. The concept of a data stream is particularly relevant for methods such as CONNECT where there is no HTTP message content after the headers.

In HTTP/1.x, the message content is generally delineated by the Content-Length header field or the `chunked` Transfer-Encoding; another request can follow on the same connection.  One of the (many) ways in which CONNECT and Upgrade are special is that in H1 it takes over the connection and makes the request extend to the end of the connection, preventing any further requests from being made.

The description attempts to be generic about method, but implicitly assumes an indefinite length stream of bytes which (in H1) is only true of CONNECT or Upgrade.  This concept is correct for what we have in mind, but the boundaries aren't crisply described right now.

@royfielding may have opinions.

**Comment by DavidSchinazi** [comment]
The sentence right after the bit you pasted is:

> Definitions of new HTTP Methods or of new HTTP Upgrade Tokens can state that their data stream uses the Capsule Protocol.

That constrains this to CONNECT/Upgrade/new methods. Is that not enough?

**Comment by MikeBishop** [comment]
I think "new methods" is probably the most questionable.  It's not clear to me that a new method can obtain the special behaviors of CONNECT.  If it were restricted to upgrade tokens (whether with HTTP/1.1 Upgrade or RFC 8441 Extended CONNECT), I think that would address the concern.

**Comment by royfielding** [comment]
I believe what he means is this definition of a data stream only holds for CONNECT requests. There is no mechanism to extend that to new request methods since all other methods are required to have length-delimited data (or no data).

**Comment by royfielding** [comment]
Likewise, I don't know of any reason we would want to support such extension methods in the future, since that is a known failure point for CONNECT. It is far simpler for a new method to require chunked or data frames.

**Comment by DavidSchinazi** [comment]
Restricting this to extended CONNECT and Upgrade sounds reasonable to me

**Comment by royfielding** [comment]
For Upgrade, the new protocol takes over after the current response is complete. Hence, the description above doesn't really work for Upgrade either.

**Comment by DavidSchinazi** [comment]
@royfielding the intent of that text was to mean "after the current response is complete" - do you have a proposal for phrasing that would work better?

**Comment by MikeBishop** [comment]
Semantics says:

> The capabilities and nature of the application-level communication after the protocol change is entirely dependent upon the new protocol(s) chosen. However, immediately after sending the 101 (Switching Protocols) response, the server is expected to continue responding to the original request as if it had received its equivalent within the new protocol (i.e., the server still has an outstanding request to satisfy after the protocol has been changed, and is expected to do so without requiring the request to be repeated).
>
> For example, if the Upgrade header field is received in a GET request and the server decides to switch protocols, it first responds with a 101 (Switching Protocols) message in HTTP/1.1 and then immediately follows that with the new protocol's equivalent of a response to a GET on the target resource. This allows a connection to be upgraded to protocols with the same semantics as HTTP without the latency cost of an additional round trip. A server must not switch protocols unless the received message semantics can be honored by the new protocol; an OPTIONS request can be honored by any protocol.
>
>The following is an example response to the above hypothetical request:
>
>     HTTP/1.1 101 Switching Protocols
>     Connection: upgrade
>     Upgrade: websocket
>     
>     [... data stream switches to websocket with an appropriate response
>     (as defined by new protocol) to the "GET /hello" request ...]

...which I think is consistent with the definition of "data stream" in this document. (And in fact uses the term "data stream" without defining it.)  That doesn't seem to match deferring the new protocol until after the response.

**Comment by royfielding** [comment]
I don't think there is any technical distinction between the two descriptions; it's nomenclature to say that what follows the CONNECT is a tunnel ended by connection closure, whereas what follows Upgrade is a different protocol that might very well come back to this one (as determined by the other protocol).
