### ISSUE TITLE
More explicit advice about what to do with datagrams related to expired tunnels

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#134]
There's a few situations where an successfully established tunnel will close. The draft covers some details about closing/terminating request streams - this seems to me to implicitly cover the HTTP datagrams related to that stream too. The way that stream resources are freed is defined by QUIC. But for datagram QUIC doesn't have much to say. It might be possible that an implementation that buffers datagrams has some options when the stream is closed. For instance, it could immediately discard those datagrams or attempt to drain the buffer and send on whatever is left. If we have some opinions on what they should do, I think it would help to state more explicitly what to do with such HTTP datagrams.

**Comment by LPardue** [comment]
On further consideration of this current text

> Endpoints MUST NOT send HTTP/3 datagrams unless the corresponding stream's send side is open. On a given endpoint, once the receive side of a stream is closed, incoming datagrams for this stream are no longer expected so the endpoint can release related state. Endpoints MAY keep state for a short time to account for reordering. Once the state is released, the endpoint MUST silently drop received associated datagrams.

I actually think we don't need to say anything. Implementations that buffer datagrams to send can be proactive if they want. Implementations that receive datagrams are instructed to silently drop them. 

CONNECT-UDP _might_ want to say something more but I don't think we need to here. Suggest close with no action.

**Comment by DavidSchinazi** [comment]
That sounds good to me. Since no one else has commented on this issue, I'm just going to go ahead and close it.
