### ISSUE TITLE
For HTTP/3, can datagrams be sent for existing method/upgrade tokens?

### ISSUE THREAD

**Issue by RyanTheOptimist** [ietf-wg-masque/draft-ietf-masque-h3-datagram#137]
This may be answered and I just missed it. After reading #135 I think that for HTTP/1 and HTTP/2 Datagrams (via capsules) can only be sent for new methods/upgrade tokens. But it wasn't clear to me if that same property was true for HTTP/3. For example, would it be valid to send HTTP/3 datagrams along with a GET request? If so, I think this means that for HTTP/3 a GET request could have both a body AND datagrams?

**Comment by DavidSchinazi** [comment]
That's a very good point. If anything, we should be prescriptive about what endpoints do if they receive a datagram associated with an existing method like GET. I suspect drop or error are the most likely candidates here.

**Comment by LPardue** [comment]
I vote for close the connection with error. 

The datagram has the relate to something in the request. If the request doesn't or cannot articulate a datagram use, it is probably broken or stupid.

**Comment by DavidSchinazi** [comment]
Since datagrams are strongly associated with a stream, I think it'd be more consistent to make this a stream error. Regardless, folks my want an extension to GET that allows sending datagrams with it, but it makes sense to require that this extension be negotiated via headers or settings first, so the semantics of such datagrams are agreed upon beforehand. So, I'm supportive of making this a stream error, with the understanding that any extension can lift this requirement between consenting parties.

**Comment by LPardue** [comment]
I'd prefer to make people suffer but I could live with a stream error.

Like you suggest, by letting people people agree on a change of requirements, we support extension. But the default of erroring helps datagram avoid the mess othat GET with body is.

But

**Comment by LPardue** [comment]
Also, I reserve the right to count the number of these failures and close the connection if it reaches my annoyance threshold 😃

**Comment by DavidSchinazi** [comment]
Ah yes `errno = ELUCASANNOYED;`. Sounds good, I'll write up a PR for this once the design team PRs are landed.

**Comment by RyanTheOptimist** [comment]
Sounds good to me. An extension could just as easily lift a connection error requirement as it could a stream error requirement in case that had any bearing on the thinking here. (A connection error might be nice because it prevents a confused peer from sending a possibly incessant stream of datagrams. On the other hand, confused peers gonna be confused and David's point about datagrams being strongly associated with a request is a good point)

**Comment by bemasc** [comment]
I think it should be a stream error to enable method-agnostic gateways and proxies, which may be multiplexing different clients' traffic onto a single next-hop connection.
