### ISSUE TITLE
Is Capsule-Protocol header mandatory?

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-masque/draft-ietf-masque-h3-datagram#151]
The text of the draft currently defines how the header works, but there's no RFC 2119 text explaining whether the client MUST or MAY send it (and the corresponding receiver behavior in case the header is missing).

**Comment by DavidSchinazi** [comment]
The draft currently states `Definitions of new HTTP Upgrade Tokens that use the Capsule Protocol MAY use the Capsule-Protocol header field to simplify intermediary processing.` - right now it's up to CONNECT-UDP / WebTransport, etc to define this normative text. Is that acceptable?

**Comment by vasilvv** [comment]
Sure, but it's not clear from the current text that the drafts have to give the specific guidance about the use of the header (the WebTransport draft currently does not).

**Comment by DavidSchinazi** [comment]
Fair enough. I suggest we replace that sentence with something along the lines of:

> HTTP endpoints SHOULD use the Capsule-Protocol header field to simplify intermediary processing. Definitions of new HTTP Upgrade Tokens that use the Capsule Protocol MAY alter this recommendation.
