### ISSUE TITLE
Section 4.3 EBNF knit:  sf-item vs. sf-boolean

### ISSUE THREAD

**Issue by philsbln** [ietf-wg-masque/draft-ietf-masque-h3-datagram#153]
Why is the ebnf `Capsule-Protocol = sf-item` instead of `Capsule-Protocol = sf-boolean`?
 Should this allow request/upgrade methods to append a list of additional parameters?

**Comment by DavidSchinazi** [comment]
Yes, `sf-item` allows parameters but `sf-boolean` does not. We didn't see a good reason to ban future parameters

**Comment by philsbln** [comment]
Maybe you should mention it and require intermediaries to pass and ignore them in case they don't understand them.

**Comment by LPardue** [comment]
as per recent changes in HTTPland specs, the ABNF adds confusion. My suggestion is to remove the ABNF. That might still leave a question over the structured types, but that is answered by the Structured Field value specs and we are unlikely to need to state anything ourselves. I can take a pass at this.
