### ISSUE TITLE
Document Structure: Describe "HTTP/3 Datagram" and "HTTP/1.1+HTTP/2 Datagram over Capsules" in the same way 

### ISSUE THREAD

**Issue by philsbln** [ietf-wg-masque/draft-ietf-masque-h3-datagram#154]
Section 3 describes HTTP/3 Datagram quite nicely.
In contrast, the corresponding contents for HTTP/1.1 and HTTP/2 are mingled with the capsule protocol documentation.

This needs some rewrite/refactoring I would be willing to file a PR for.

**Comment by DavidSchinazi** [comment]
Seeing a PR for what you have in mind would definitely be very helpful, thanks!

**Comment by philsbln** [comment]
Sorry, I overlooked PR #152 – my PR would have looked very similar, so #152 would IMHO close this issue and I will review/make suggestions on #152 instead.

**Comment by DavidSchinazi** [comment]
Thanks, I'll close this issue then.
