### ISSUE TITLE
Consider rephrasing H3_DATAGRAM setting text

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#163]
The current text talks about "supporting" HTTP/3 datagrams. It seems we could tighten this up to be more about the willingness to receive datagrams a la https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#section-6.5.2

**Comment by DavidSchinazi** [comment]
SGTM
