### ISSUE TITLE
Clarify sentence

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-h3-datagram#164]
End of section 3.3. (error handing) says:

`When a stream carrying capsules terminates cleanly, if the last capsule on the stream was truncated, this MUST be treated as a malformed or incomplete message.`

 Not sure I can parse that sentence correctly. Is that

`When a stream carrying capsules terminates cleanly BUT the last capsule on the stream was truncated, this MUST be treated as a malformed or incomplete message.`

?

**Comment by LPardue** [comment]
"terminates cleanly" is an abstract way of covering all HTTP versions notion of a stream FIN. This is not well defined (maybe lost in one of the restructuring edits?).

If we think of HTTP/3 and the request stream being FIN'd at a particular offset, that is independent of a parser acting on the data in the stream.

I think the way to make this clearer is to define or reference stream closures in respective HTTP docs.

**Comment by mirjak** [comment]
I don't understand the sentence structure here: When ..., if ..., then. Why is there a when and an if with a comma? May this should be: When ... and if ..., then?

Sorry if that is grammatically correct but it really confuses me what the sentence is supposed to say...

P.S.: clarifying the term "terminates cleanly" is also a good idea though.

**Comment by mirjak** [comment]
Yes, that works for me. Thanks!
