### ISSUE TITLE
Introduction: Missmatching description of relation to HTTP or underlying transport.

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-h3-datagram#172]
Section 1.

"When the underlying transport protocol supports unreliable delivery (such as when the QUIC DATAGRAM extension is available in HTTP/3), they can use that capability."

"This document also describes the HTTP Capsule Protocol in Section 3, to allow conveyance of HTTP Datagrams when the QUIC DATAGRAM frame is unavailable or undesirable, such as when earlier versions of HTTP are in use."

To me there is a bit of mismatch between these two sentences and what HTTP/3 is prior to this extension.

The first indicate that datagram support is a capability of the underlying transport for the HTTP version but then link it hard to HTTP/3. While the HTTP/3 support is dependent on this extension in addition to a QUIC stack having Datagram support. While the second takes it as a property of the HTTP version, where it is assumed that earlier version can't support this, i.e. those that are defined to use TCP only. 

Technically a HTTP/3 endpoint with a QUIC stack without datagram support can  use capsules and this document does not require an endpoint to support QUIC datagram.

And the second statement should likely use a statement saying like …  unavailable or undesirable, such as when TCP is used as transport protocol as with HTTP/1.x and HTTP/2.

**Comment by LPardue** [comment]
Fair point, HTTP 1 and 2 don't strictly require TCP either.

I think we can tweak these opening paragraphs a little to be more consistent and clear.

**Comment by DavidSchinazi** [comment]
SGTM
