### ISSUE TITLE
Default endpoint behaviour of unknown capsule types

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-h3-datagram#173]
I don't think this was discussed previously in detail and the answer might just be no but would like to discuss this before we finally publish this spec.

There are two default behaviours specified:

- intermediaries should/must forward unknown capsule types unaltered, and
- endpoints must silently drop unknown capsule types.

The protocol would be more flexible if e.g. one could also instruct intermediates to drop and send an error instead, and if endpoints could be instructed to either drop silently or send an error. If any such behaviour would be useful, we need to define now e.g. by using two flags as part of the type field. Of course adding those flags would make the protocol also slightly more complicated. 

So just to be sure we do the right thing: are we sure we don't need to support this future flexibility and have selected the right default behaviour? Or are there any use cases where a different default behaviour would be required?

**Comment by LPardue** [comment]
Sending errors for unknown things doesn't really align with our attempts in HTTP land to avoid ossification in implementations (aka GREASING).

If there is some use of a capsule that needs acknowledgement it was received and/or processed, then that capsule should build the mechanism; be it either on a per-capsule basis or an upfront negotiation of capabilities before the capsule flow commences.

Our current error signaling mechanisms (stream or connection error) are terminal for a stream.. But I'm not seeing much value in trying to define an abstract error generation pattern just for capsules, without a concrete use case.

**Comment by DavidSchinazi** [comment]
@mirjak do you have an example of a use-case that would benefit from the erroring scheme? I'm not seeing any - it's more future-proof to drop at the endpoints and use new HTTP headers to indicate support for new capsules.

**Comment by mirjak** [comment]
If you negotiate all supported capsule types using http headers (or something else), isn't receiving an unknown capsulate type not automatically an error (and you should close the connection)?

**Comment by LPardue** [comment]
In my experience, closing connections in such cases is a way to build fragility into the deployment architecture, and achieves the opposite of the flexibility goal.

**Comment by DavidSchinazi** [comment]
Making this an error would also prevent sending capsules alongside the request. I really don't see the value of this proposed change.

**Comment by DavidSchinazi** [comment]
I'm proposing we close this issue with no action.

@mirjak if you have a specific use case that requires this new error scheme, then please share it.

**Comment by mirjak** [comment]
My initial issue was about providing one or more flags to impact the handling of unknown capsule types. I already noted that this add a bit of complexity but might provide higher flexibility for future extension. I don't have a use cases but wanted to trigger the discussion to ensure we didn't miss use case. Therefore I would like to keep this issue open a bit longer to see if more people have input or bring it to the list for discussion.

However, there is a second question here which is, if we don't have these flags, did we select the right default behaviour. For intermediaries I think the answer is clear, as the whole point of this protocol is to have a mechanism that can transverse an intermediary unaltered even if unknown to the intermediary (and there is a separate about having a MUST or SHOULD there, however that discussion drifted a bit in a different direction). However, for the endpoint I not sure anymore we have chosen the right default behaviour. Currently the default is silent drop, however, as Lucas mention, an endpoint should never get into the situation where it receives an unknown capsule type as there always needs to be some negotiation that also defines the set of capsules that are support. There receiving a capsule type is actually protocol error and should probably treated similarly to all other protocol errors.

**Comment by LPardue** [comment]
> Currently the default is silent drop, however, as Lucas mentioned, an endpoint should never get into the situation where it receives an unknown capsule type as there always needs to be some negotiation that also defines the set of capsules that are supported. Therefore receiving an unknown capsule type is actually a protocol error and should probably treated similarly to all other protocol errors.

I'm not sure I meant to say that. 

If you're a receiving *endpoint*, you should be able to handle unknown capsules without error. That would allow someone to, for example, use the "connect-udp" token and extend it's behaviour via new capsule types that were not thought of at the time that "connect-udp" was invented. This is a property of HTTP/2 and HTTP/3 frames and streams already, and seems to me something we should emulate in capsule, we already define "reserved types for GREASING".

If we prevent unknown types unless prearranged, I can see that leading to a need for proliferation of e.g. upgrade tokens, which to my mind would not be a good way to design the system.

**Comment by DavidSchinazi** [comment]
+1 to Lucas: silent drop enables grease and new kinds of extensions.

Mirja: Happy to keep this issue around for the duration of the WGLC to see if anyone else has use-cases that benefit from this new error scheme.

**Comment by mirjak** [comment]
If we want this kind of additional extensibility, I think we should add a flag to have both options: just ignore or please tell me if you don't understand because otherwise we have to re-invent some kind of ACK scheme for each new type that we want to deploy this way.

**Comment by DavidSchinazi** [comment]
That flag can be added as a new extension. There's no use case for it so I don't see any reason to include in the base spec

**Comment by DavidSchinazi** [comment]
Closing this since today marks the end of WGLC and we haven't seen any use cases for this proposed error scheme.
