### ISSUE TITLE
What exactly is negotiated using a Setting?

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-h3-datagram#174]
In Section 2: 

"Negotiation is achieved using a setting; see Section 2.1.1."

So first I though this was just lacking an "HTTP" prior to the setting. But, I think this glosses over the general negotiation complications across versions. In this section when the high level functionality is defined, I think actually the question of negotiation in general needs to be discussed, not only for HTTP/3.

**Comment by DavidSchinazi** [comment]
I think we can improve clarity here. Right now we have `Negotiation is achieved using a setting; see Section 2.1.1.` in the "HTTP Datagrams" section. We should spell it out better, maybe: `Negotiating the ability to transmit HTTP Datagrams using QUIC DATAGRAM frames is achieved using an HTTP/3 setting; see Section 2.1.1.`

**Comment by LPardue** [comment]
WFM
