### ISSUE TITLE
Section 2: Reference to "stream" which may not be a stream

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-h3-datagram#175]
Section 2:

"HTTP Datagrams MUST only be sent with an association to a stream whose HTTP semantics explicitly supports HTTP Datagrams."

I think the reference to "stream" is unclear here. Is the intention here to refer to "HTTP Message" or "HTTP Method" that would then in HTTP/2 and HTTP/3 map to a stream? Anyway align with next paragraph that uses "Method".

**Comment by LPardue** [comment]
The subsequent use of "method" is not great. I would substitute both with "request" e.g. 

"HTTP Datagrams MUST only be sent with an association to an HTTP request that explicitly supports them."
...

"If an HTTP Datagram is received and it is associated with a request that does not support it HTTP Datagrams, the receiver MUST terminate the request...."

**Comment by DavidSchinazi** [comment]
Agreed, switching to request would be clearer
