### ISSUE TITLE
Datagram related state is not well-defined

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-h3-datagram#176]
The draft currently states:
> HTTP/3 Datagrams MUST NOT be sent unless the corresponding stream's send side is open. Once the receive side of a stream is closed, incoming datagrams for this stream are no longer expected so related state can be released. State MAY be kept for a short time to account for reordering. Once the state is released, the received associated datagrams MUST be silently dropped.

However in PR #161, @mirjak points out that this "state" is not well defined. I agree, we should fix it.

Thinking about this more, I don't think we need the concept of related state. We can instead just say that received datagrams MUST be silently dropped if the stream receive side is closed.

**Comment by mirjak** [comment]
I agree with removing the concept of state is better. I don't want to be overly nitty and the proposed sentence is better but there also nothing like "the stream receive side", as there can be multiple streams (open and closed), that's why I proposed

`If a datagram is received without associated state, the received datagrams MUST be silently dropped.`

Or if we don't want state, then it would be:

`If a datagram is received without an associated (open) stream, the received datagrams MUST be silently dropped.`

**Comment by DavidSchinazi** [comment]
That's not quite right: there cannot be multiple streams, as datagrams are strongly associated with a client-initiated bidirectional stream. I'd phrase the paragraph as:

> HTTP/3 Datagrams MUST NOT be sent unless the corresponding stream's send side is
open. If a datagram is received after the receive side of the corresponding stream is closed,
the received datagrams MUST be silently dropped.

**Comment by mirjak** [comment]
That works. Thanks!

**Comment by martinthomson** [comment]
This answer is necessary because QUIC doesn't guarantee ordering, but is this necessarily true indefinitely?  But can I regard a datagram that arrives an hour after the stream closes as an error?

**Comment by DavidSchinazi** [comment]
If you keep track of QUIC packet numbers, you can see that the peer closed the stream before it sent the datagram which means they violated a MUST. You're welcome to error if you detect that, but I don't think we should mandate this level of tracking.

**Comment by martinthomson** [comment]
I'm not sure that that is a good strategy given how some deployments manage their packet numbers.  I'm talking about maybe running a really long timer.

**Comment by DavidSchinazi** [comment]
That introduces a way for an attacker to cause connection closure by delaying a specific packet. What problem are you trying to solve?

**Comment by martinthomson** [comment]
Good point.  I thought that we did similar in a few places in QUIC.  As you say, it's possible to enforce, but tricky.  The concern I'd have is that this effectively forbids enforcement, but maybe that's OK.
