### ISSUE TITLE
Use HTTP style for referencing HTTP/2 and HTTP/3

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#178]
s/[H2]/[HTTP/2]
s/[H3]/[HTTP/3]

Due to tooling, the way to make this work is quite annoying so we will probably want to wait until that cluster is published

**Comment by DavidSchinazi** [comment]
SGTM, happy to defer this until AUTH48 if tooling makes it tricky
