### ISSUE TITLE
IANA Policy for new Capsule Type registry

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-h3-datagram#189]
When the first IANA registry was added to this document, it used "First Come First Served" to save time. This got carried over through the various changes and now the new "Capsule Type" registry is still marked that way. But in that corresponding time, the QUIC WG came up with a very good IANA policy for varint registries and documented it in RFC 9000. We should adopt that policy for Capsule Types.

**Comment by gloinul** [comment]
I would like to note that changes like this is not editorial, it is something that should have consensus call.

**Comment by DavidSchinazi** [comment]
Hi Magnus, I agree that this issue is not editorial. That's why I brought it up on this list over a week ago in its own thread ([see here](https://mailarchive.ietf.org/arch/msg/masque/LCgkI6Z8uMeQWmPCDV1Ixf79Ar0/)). This received two approvals on [the PR](https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/pull/191) and no other comments or concerns.
