### ISSUE TITLE
0-RTT and greater than or equal formulation for SETTINGS_H3_DATAGRAM

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-h3-datagram#195]
Section 2.2.1:

" When servers decide to accept
   0-RTT data, they MUST send a SETTINGS_H3_DATAGRAM setting greater
   than or equal to the value they sent to the client in the connection
   where they sent them the NewSessionTicket message."

As the SETTINGS_H3_DATAGRAM only allows value 0 or 1 is this just a way of
saying: Servers that accept 0-RTT data and have previously accepted HTTP Datagram and provide a session ticket MUST accept them for future connections referencing that ticket. ?

 I would also note that the sentence become unclear if it the value or setting itself that are equal or greater if there is a difference between these two. Considering that one talk about value in earlier sentences one might want to make that distinction in this paragraph too.

**Comment by DavidSchinazi** [comment]
Hi Magnus, I don't understand this editorial issue. Can you clarify what is unclear to you? In what way are you not understanding this paragraph?

**Comment by gloinul** [comment]
@DavidSchinazi is my paraphrasing correct? 

If that is the case, I think the formulation is unnecessary convoluted and also hides an aspect. I reacted on the greater value for something that is only 0 or 1.

**Comment by LPardue** [comment]
The text seems precise enough to me. 
For the setting, 0 = off, 1 = on. You can't renage what you gave the client on a previous connection and go from 1 -> 0. But you can upgrade them and go from 0 => 1. Or you can send a setting with an identical value.

Since 1 is the maximum value defined by the setting, it seems trivial for a server to do the right thing with picking whether to send 0 or 1.

**Comment by DavidSchinazi** [comment]
@gloinul your paraphrasing is correct, though it's not precise enough for a normative requirement. Given that the current normative text is precise and unambiguous even if slightly convoluted I'm inclined to keep it as is. The fact that your paraphrasing was correct demonstrates that this text is clear enough.

**Comment by tfpauly** [comment]
The longer form to be normatively correct would be something like this, I imagine:

> When clients use 0-RTT, they MAY store the value of the server's SETTINGS_H3_DATAGRAM setting. Doing so allows the client to send QUIC DATAGRAM frames in 0-RTT packets. When a server decides to accept 0-RTT data, it MUST send a SETTINGS_H3_DATAGRAM setting with a value of 1 if the previous value was 1 in the connection where it sent the client the NewSessionTicket message. If the previous value was 0, the server MAY send a value of either 0 or 1. If a client stores the value of the SETTINGS_H3_DATAGRAM setting with its 0-RTT state, it MUST validate that the new value of the SETTINGS_H3_DATAGRAM setting sent by the server in the handshake is 1 if the previous value was 1; if not, the client MUST terminate the connection with error H3_SETTINGS_ERROR. In all cases, the only two permitted value of the SETTINGS_H3_DATAGRAM setting parameter are 0 and 1.

I don't think that greatly improves the text, but it is a bit more explicit.

**Comment by gloinul** [comment]
Ok, then lets close this issue.
