### ISSUE TITLE
To what does "these goals" refer? (comment 2)

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#209]
To what does "these goals" refer?
                                                                                                   
Original: 
When HTTP Datagrams are conveyed on an HTTP/3 connection, the QUIC
DATAGRAM frame can be used to achieve these goals, including unreliable
delivery; see [Section 2.1](https://www.rfc-editor.org/authors/rfc9298.html#section-2.1)

**Comment by LPardue** [comment]
yeah, this text seems weird. Perhaps

> When HTTP Datagrams are conveyed, demulitplexing and unreliable delivery is provided by the QUIC DATAGRAM framel see Section 2.1.

**Comment by DavidSchinazi** [comment]
Or how about simply

> When HTTP Datagrams are conveyed on an HTTP/3 connection, the QUIC DATAGRAM frame can be used to achieve unreliable delivery; see [Section 2.1](https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/auth48/draft-ietf-masque-h3-datagram.html#format).

**Comment by LPardue** [comment]
I made typos in my suggestion that doesn't help, sorry.

IIRC the original text is a roundabout way of saying - we use a special payload in QUIC datagrams in order to achieve unreliable datagram multiplexing. This makes more sense in the context of the next [para](https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/draft-ietf-masque-h3-datagram.html#section-2-3) that then states HTTP/2 frames provide demultiplexing.

**Comment by DavidSchinazi** [comment]
Right, how about

> When HTTP Datagrams are conveyed on an HTTP/3 connection, the QUIC DATAGRAM frame can be used to provide demultiplexing and unreliable delivery; see [Section 2.1](https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/auth48/draft-ietf-masque-h3-datagram.html#format).
