### ISSUE TITLE
We suggest rephrasing this sentence (comment 4)

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#211]
We suggest rephrasing this sentence. The phrase "might have practical barriers to determining..." is difficult to parse. Does the suggested text below accurately convey the intended meaning?

Original:
Generating an error is not mandatory in this case because HTTP/3
implementations might have practical barriers to determining the
active stream concurrency limit that is applied by the QUIC layer.

Perhaps:
Generating an error is not mandatory in this case because HTTP/3
implementations might present practical barriers when determining the
active stream concurrency limit that is applied by the QUIC layer.

**Comment by LPardue** [comment]
The point we're making here is that the implementations might encounter barriers, either because they contain them, or the API the are using presents them. The suggestion doesn't cover these two response.

Alternative Perhaps:
Generating an error is not mandatory in this case because there
might be practical barriers that prevent HTTP/3 implementations
from determining the active stream concurrency at the QUIC layer.

**Comment by DavidSchinazi** [comment]
How about we just nuke this sentence?

**Comment by LPardue** [comment]
I've just rememberd this text is verbatim copied from https://www.rfc-editor.org/rfc/rfc9218.html#section-7.2-6

ADs seem to like justifcations for SHOULD requirements.

If we're worried about verbosity, then how about

Generating an error is not mandatory because the QUIC stream limit may be unknown to the HTTP/3 layer.

**Comment by DavidSchinazi** [comment]
That works for me
