### ISSUE TITLE
In the description of Figure 3, should "Type" be lowercased here? (comment 5)

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#212]
In the description of Figure 3, should "Type" be
     lowercased here?  We see lowercased forms of "length" and "value"
     in the two entries below this for "Capsule Length" and "Capsule
     Value", respectively.

Original:

       Capsule Type:  A variable-length integer indicating the Type of the
          capsule.

**Comment by LPardue** [comment]
This seems sensible.

**Comment by DavidSchinazi** [comment]
That works for me
