### ISSUE TITLE
For the ease of the reader, may we rephrase this text as follows? (comment 6)

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#213]
For the ease of the reader, may we rephrase this text as
     follows?  Or is there another way to rephrase?

Original:

       Capsule Length:  The length in bytes of the Capsule Value field
       following this field, encoded as a variable-length integer.

Perhaps:
   Capsule Length:  The length, in bytes, of the Capsule Value field,
   which follows this field, encoded as a variable-length integer.

**Comment by LPardue** [comment]
I might try and avoid one comma with:

Capsule Length: The length, in bytes, of the following Capsule Value field
, encoded as a variable-length integer.

**Comment by DavidSchinazi** [comment]
I'd prefer to keep "following this field", so slight preference for what the RFC editor proposed

**Comment by LPardue** [comment]
that works for me, lets go with it.
