### ISSUE TITLE
Is it really the Definition that performs the security analysis? (comment 9)

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#216]
Is it really the Definition that performs the security
     analysis?

Original:
Definitions of new HTTP Upgrade Tokens that use the Capsule
Protocol need to perform a security analysis that considers
the impact of HTTP Datagrams and Capsules in the context of
their protocol.

Perhaps:
Definitions of new HTTP Upgrade Tokens that use the Capsule Protocol
need to include a security analysis that considers the impact of HTTP
Datagrams and Capsules in the context of their protocol.

**Comment by LPardue** [comment]
I prefer the RFC editor suggestion here.

**Comment by DavidSchinazi** [comment]
Same, works for me
