### ISSUE TITLE
We had the following questions related to terminology use (comment 12)

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#219]
We had the following questions related to terminology use:

a) The following terminology appears to be used inconsistently. Please
review these occurrences and let us know if/how they may be made
consistent.

capsule protocol vs. Capsule Protocol (may need an IANA update)

Upgrade token vs. Upgrade Token (note that RFC-to-be 9297 contained a question about "connect-udp" HTTP Upgrade Token vs. "connect-udp" upgrade token)

capsule type vs. Capsule Type (should "field" follow the capped version?)

capsule vs. Capsule (generally)

b) RFC 9000 uses "stream ID".  Should "Quarter Stream ID" be made "Quarter stream ID"?  This would match the use of "QUIC stream ID" in this document as well.

c) Please review the use of quotes with header field (and possibly field) names.  The companion document (draft-ietf-masque-connect-udp-15) most frequently uses double quotes around header field names.  Should this document do the same?

d) May we update to use "Item Structured field" (with field lowercase) to match other field names?  FYI: RFC 8941 uses "Item Structured Header".

**Comment by LPardue** [comment]
we should figure this out in tandem with CONNECT-UDP.

Captalization of our new terms is on us. But the HTTP stuff stuff  should defer to the HTTP style guide https://httpwg.org/admin/editors/style-guide; meaning 

- > When defining a field, the first instance should be quoted
- > When referring to a field defined in a different document, the first instance should include a reference, and all instances should be unquoted
- Use the suggested style of importing Structured fields types. To address d) then just say "The "Capsule-Protocol" header field is an Item"

**Comment by LPardue** [comment]
And while we're here: 

1) HTTP style prefers that citations use the label `[STRUCTURED-FIELDS]`.

2) I wonder if we should label the reference to QUIC DATAGRAM with a prefix like `[QUIC-DGRAM]`, which would line up clearly against `[HTTP-DGRAM]` without confusion.

**Comment by DavidSchinazi** [comment]
a) I like capitalizing our new terms
b) I prefer Quarter Stream ID over Quarter stream ID but I don't care too much
c) Happy to follow HTTP style guide for quoting of headers
d) sure
1.  Sure I'm ok with STRUCTURED-FIELDS
2. Sure QUIC-DGRAM sounds good

**Comment by DavidSchinazi** [comment]
Also let's use "upgrade token" without capitals to match RFC 9110
