### ISSUE TITLE
packing DATAGRAMs with the same flow-id in a single QUIC packet

### ISSUE THREAD

**Issue by lnicco** [ietf-wg-masque/draft-ietf-masque-h3-datagram#26]
in Section 2 "Flow Identifiers" it reads 

> If multiple DATAGRAM frames can be packed into a single QUIC packet, the sender SHOULD group them by flow identifier to promote fate-sharing within a specific flow and improve the ability to process batches of datagram messages efficiently on the receiver.

this to me seems to be in conflict with the opening statement 
> QUIC DATAGRAM frames do not provide a means to demultiplex application contexts

if the flow-id is in the DATAGRAM payload, the transport is not supposed to be peeking at it. While it could be a nice (but a bit hacky) optimization in a real-world implementation, I feel like the RFC having it as a SHOULD is not ideal.

**Comment by DavidSchinazi** [comment]
In my experience, in order to build a high performance implementation of QUIC, you have to leverage the fact that layers can share information to improve performance. Are you saying that you'd prefer not using SHOULD for this kind of optimization?

**Comment by LPardue** [comment]
I think Luca might have a point. If we consider this as a feature that a transport provides as a service, I don't really know what the service provides. There isn't another transport mechanism that relies on the ordering, or an interoperable aspect (would the other side be able to detect this?). It seems this is an aspect more about the API that QUIC provides, which is going to be a rich field of opportunity. There could be benefits but I don't know if we need to use the SHOULD. We could probably relax the language and try to articulate the benefits or tradeoffs of packetization and frame bundling. For instance, batching might interfere with timeliness, and controlling that might start creeping into prioritisation territory.

The more I think about it, the described behaviour about batch processing might assume the receiver behaves a certain way, which might not be true. Therefore this might not be a good default to recommend.

**Comment by DavidSchinazi** [comment]
Fair enough. Perhaps we remove this for now, and add guidance once we have more implementation/deployment experience?

**Comment by LPardue** [comment]
I can live with a less drastic edit, leaving the text in draws the reader attention to the idea that packing could be important. I'd be happy to put together an editorial replacement for review, and if we hate it, then drop the concrete recommendation?

**Comment by lnicco** [comment]
Thanks Lucas, you framed it way better than I could. 
Also I believe that whether shared-fate within a flow is desirable or not may depend on the application.

**Comment by dtikhonov** [comment]
> whether shared-fate within a flow is desirable or not may depend on the application.

I came here looking for the same information:  Why is fate-sharing desired?  Is there some background to this?
