### ISSUE TITLE
Make it explicit that Flow IDs are non-negative

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#27]
The draft doesn't do this. It relies on the QUIC varint encoding for non-negativity in DATAGRAM frames but `sf-integer` could contain a negative value. Let's be clear in the spec.

**Comment by DavidSchinazi** [comment]
Definitely agree, could you write a PR please?

**Comment by LPardue** [comment]
I will.

**Comment by LPardue** [comment]
fixed in https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/pull/29
