### ISSUE TITLE
Datagram flows should have their individual max datagram size

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-masque/draft-ietf-masque-h3-datagram#28]
Consider a situation where a single HTTP/3 connection is terminated at a CDN and it carries two different WebTransport sessions to different backends.  Those backends may have different max datagram size, thus the protocol needs to be able to specify max datagram size limit per-flow.

**Comment by LPardue** [comment]
Do you mean DATAGRAM frame? Theres still an open question about whether we will continue with the max size Transport Parameter as a integer, or whether plain enable / disable would work

**Comment by DavidSchinazi** [comment]
I'm not sure whether this feature would be useful. Since datagram-based applications already need to perform PMTUD because the MTU might vary on each hop, I don't think there's much value in propagating the value of the transport parameter.

**Comment by DavidSchinazi** [comment]
Discussed this offline with @vasilvv. Given that the MTU can change mid-flow for each hop, propagating this information to both endpoints is non-trivial. This means there are two solutions:
1. applications that use datagrams perform their own end-to-end PMTUD
2. a future extension to HTTP/3 datagrams could define a way to communicate this

In both cases, we don't need to address this now in the HTTP/3 datagrams draft, so I'm closing this issue.
