### ISSUE TITLE
Is it an error to receive a flow ID greater than 10^15-1?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#31]
There's a disparity between the largest flow ID that can be carried in the DATAGRAM frame and the largest that we can express in Datagram-Flow-Id.

Draft 00 prevents a flow ID allocation of >= 10^15-1 but doesn't seem to address the case where a DATAGRAM frame contains that value. This is clearly an error, and I'd suggest that it is a connection error; probably `H3_ID_ERROR` or some new codepoint if we really wanted.

**Comment by DavidSchinazi** [comment]
I don't think that needs to be an error, we can simply treat this like any other unknown flow ID?

**Comment by LPardue** [comment]
IMO this is clearly a situation that shouldn't happen and indicates the sending endpoint probably has some bug. I'm not sure on what being silent on the matter helps.

**Comment by DavidSchinazi** [comment]
This issue is no longer relevant now that we have merged #52, closing.
