### ISSUE TITLE
What guarantees are there against re-using flow IDs

### ISSUE THREAD

**Issue by ianswett** [ietf-wg-masque/draft-ietf-masque-h3-datagram#32]
QUIC has strong guarantees on not re-using Stream IDs.

There was strong consensus against allowing re-use of Flow IDs(#22).  The WG today was also leaning towards creating flow IDs that are not related to the Stream ID, which means preventing Flow ID re-use may be a challenge, since we can't rely on Stream ID non-reuse.

Options for enforcement include best effort ie: "MUST close the connection if reuse is detected" or try to ensure datagram flow IDs are used in order, which could allow enforcement be mandated.

**Comment by DavidSchinazi** [comment]
I agree that we don't currently have text about enforcing the prohibition on reuse. But I'm not sure this is a feature we need? QUIC stream creation is flow controlled (via MAX_STREAMS) so there is infrastructure for this. QUIC Datagram Flow creation is not flow controlled, so I don't see this as a direct mapping. Do you have a use case that would require or benefit from this enforcement?

**Comment by ianswett** [comment]
I do not.

Given that, I think a "MUST close the connection if reuse is detected" approach seems fine, but it's worth documenting.

**Comment by DavidSchinazi** [comment]
To clarify, reusing a flow ID for _different_ uses will be disallowed by the PR that resolves #22. However, two requests can refer to the same flow ID for the _same_ usage, that will stay legal. Because of this, I wouldn't know how to implement the MUST you describe.

**Comment by ianswett** [comment]
I filed #33 for two requests referring to a single flow ID.

**Comment by DavidSchinazi** [comment]
This issue is no longer relevant now that we have merged #52, closing.
