### ISSUE TITLE
Allowing a single flow ID to be associated with multiple requests is brittle

### ISSUE THREAD

**Issue by ianswett** [ietf-wg-masque/draft-ietf-masque-h3-datagram#33]
The only note in the draft I see about this is:
"If an intermediary processes distinct HTTP requests that refer to the same flow ID in their respective "Datagram-Flow-Id" header fields, it MUST ensure that those requests are routed to the same backend."

This is not a requirement our load balancer would be able to enforce, since requests are routed to backends individually.  Is there a use case that really needs this, because it feels very odd to me as well as not working for our deployment.

**Comment by DavidSchinazi** [comment]
@ianswett we're going to have to change our load balancer to handle datagrams, so the fact that it only deals in requests today doesn't mean it'll behave a given way once it supports MASQUE and/or WebTransport. In particular we're going to need a map from datagram flow ID to backend no matter what we do, so checking that map on incoming requests isn't unreasonable.

The current example use-case for this feature is [draft-pauly-masque-quic-proxy-00](https://tools.ietf.org/html/draft-pauly-masque-quic-proxy-00).

**Comment by afrind** [comment]
In order to meet the requirement, I think you cannot have a 1:N mapping between flow ID and request stream.  If there were more than one stream that used the same flow ID, and those streams were routed to different backends, there would be no way to choose which to deliver an incoming datagram to (or are you supposed to replicate it?)

**Comment by DavidSchinazi** [comment]
This issue is no longer relevant now that we have merged #52, closing.
