### ISSUE TITLE
Why are flow IDs named?

### ISSUE THREAD

**Issue by ianswett** [ietf-wg-masque/draft-ietf-masque-h3-datagram#34]
I spent a while trying to understand this and it's not clear to me from the spec.  Lucas posted this on Issue #24, but it's not quite enough for me(and it's not in the document).

> My understanding of the ask that lead to the "name parameter" being defined in draft-schinazi-masque-h3-datagram-04 was that we want to be able to assign unique handles to flow IDs in a generic way that is part of the this document. That would allow a general purpose implementation to be able to disambiguate lows without having to understand any specific extension.

_Originally posted by @LPardue in https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/issues/24#issuecomment-759095560_

**Comment by achernya** [comment]
I think we should remove the flow ID names. The document appears to try to create a semantic meaning for them, but it has no effect on the wire image, so we can (and IMO should) do the semantic meanings in application level code.

**Comment by DavidSchinazi** [comment]
This issue is no longer relevant now that we have merged #52, closing.
