### ISSUE TITLE
Directionality of flow/context IDs

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-h3-datagram#42]
In draft-ietf-masque-h3-datagram-00, flow IDs are bidirectional. During the 2021-04 MASQUE Interim, we discussed the possibility of making them unidirectional. Here are the differences:

* Bidirectional
  * single shared namespace for both endpoints (even for client, odd for server)
  * it's easier to refer to peer's IDs, which makes negotiation easier

* Unidirectional
  * one namespace per direction
  * every bidirectional use needs to associate both directions somehow

I'm personally leaning towards keeping them bidirectional. Unlike QUIC streams, these do not have a state machine or flow control credits, so there is no cost to only using a single direction of a bidirectional flow for unidirectional use-cases.

**Comment by LPardue** [comment]
There's another option where flows are unidirectional but they share a namespace (cleint even/server odd).

I'm undecided. And I also don't know how important it is to choose. The 2 layer design means that DATAGRAMs always have a bidirectional tie via the stream ID.

On balance, I think bidirectional would be good enough today but I would be receptive to extension use cases that make a strong point of unidirectional.

**Comment by tfpauly** [comment]
🤷 Bidirectional is my personal preference, but either way could work ultimately. It seems to me that any extension that wants unidirectional can just only use this context/flow/etc ID for one direction if it wants.

**Comment by bemasc** [comment]
I think bidirectional flows are likely overcomplicated and unnecessary.  For example, if either peer can "close" a flow, this requires a much more complex state machine.  In my experience, half-closed states are hard to get right.  Closing unidirectional flows seems much easier to reason about.

Many, perhaps most, of our use cases for flows are really unidirectional.  For example, DSCP marking likely only makes sense from client to server, while timestamps for congestion control tuning likely only make sense from server to client.  QUIC connection IDs are different in each direction, so QUIC header compression may be easiest to understand with unidirectional flows.

**Comment by DavidSchinazi** [comment]
> In my experience, half-closed states are hard to get right.

Bidirectional doesn't imply half-close states. I'm thinking of a bidirectional flow that can only be closed atomically as a whole.

> Many, perhaps most, of our use cases for flows are really unidirectional.

I don't think that's true. The default extension-less CONNECT-UDP is bidirectional. So is ECN, and so would a timestamp extension.

**Comment by achernya** [comment]
I would prefer bidirectional without support for half-close. I feel that having unidirectional flow/context IDs adds overhead we don't need; peers now need to track those associations and it's unclear what the benefits of having them separated out are.

**Comment by martinduke** [comment]
This issue is conflating consent (unilateral/bilateral) with scope (unidirectional/bidirectional). IIUC there are two questions here:
1) Can I send a flow-id forever once declared, or can the endpoint tell me to stop without killing the whole stream (consent)?
2) Can the receiver of a flow-id assignment use that same flow-id when sending datagrams, or could this mean something completely different?

I think the answer to (1) is "yes, it can tell me to stop" (i.e. it is negotiated while allowing speculative sending). For (2), I lean toward bidirectional, but not strongly. There are plenty of codepoints, so it seems wasteful for each endpoint to define the same semantic explicitly.

**Comment by DavidSchinazi** [comment]
@martinduke the intent of this issue wan't to conflate those two things. This issue is about scope. For consent, see issue #43.

**Comment by afrind** [comment]
Conceptually, I like unidirectional better.  I tell the peer that when I send with context-ID=X, it has a given semantic.  For bidirectional the sender is saying both that and that if the peer sends on that ID the original sender will interpret with the same semantic.  That might not even make sense.

Is it possible to associate datagrams with a unidirectional stream (push?).  If so, does allowing for bidirectional context imply that even though the receiver cannot send frames on the stream, it can send datagrams?

Every negotiation does run the risk of loss/reordering resulting in a drop or buffering event at the receiver.  The appeal of bidirectional is that it removes half of this risk in the cases where the bidirectionality is used.

**Comment by ianswett** [comment]
To second @achernya I would also prefer bidirectional without support for half-close.  Given you can always not send something in one direction, and there's none of the overhead of streams(ie: flow control, etc) I can't see any benefits of unidirectional over bidirectional in this case.

Associating h3-datagrams with a server push seems like unnecessary complexity to me, but you're right that it should be clarified.  #47
