### ISSUE TITLE
Can HTTP server push use h3-datagram?

### ISSUE THREAD

**Issue by ianswett** [ietf-wg-masque/draft-ietf-masque-h3-datagram#47]
I would prefer that h3-datagram cannot use server push, because I believe it adds extra complexity and there are no clear use cases.

Additionally, server push is an optimization which allows a server to push a resource up to 1RTT prior to the client's (expected) requests for the resource.  h3-datagram is much more analogous to a CONNECT, which is neither idempotent or cacheable, so I'd assume a client would drop any received datagrams, rendering the optimization useless.

Whatever we decide, we should definitely clarify this.  This issue was motivated by https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/issues/42#issuecomment-827750984

**Comment by LPardue** [comment]
+1

I think it would be OK to restrict this H3 DGRAM extension to only permit top-level flow creation by the client. This gels well with HTTP semantics - today there isn't a way for a server to spontaneously start sending things not associated with an HTTP request. Even server push needs the "parent request" (unless you try to do something like my unbound server push extension, which no one seemed interested in).

In a two layer model, there might be use cases that benefit from sever-initated second-level flows. But they can hang off the client request stream, not try to tack on to server push.

Finally, descoping server push means that support over multiple proxies becomes much easier to reason about.

**Comment by ianswett** [comment]
Thanks @LPardue I forgot to mention that server push via multiple layers of proxies(ie: CDNs) has proven fairly impossible in practice, and h3-datagram is intended as an end-to-end protocol I believe.

**Comment by afrind** [comment]
The use-case I could see for push leveraging datagram is if the server wanted a mechanism to deliver the body of the pushed resource in an unreliable way, but the same could most likely be accomplished by hanging the datagrams off the associated stream of the push.  

> server push via multiple layers of proxies(ie: CDNs) has proven fairly impossible in practice

Really?  We've delivered pushes through multiple layers of proxies.  It's not going to be that different for WebTransport streams to traverse proxies.

**Comment by ianswett** [comment]
I think there are better ways to send unreliable bodies than unreliable datagrams.

I agree that in some homogeneous environments, multi-layer pushes are practical, but in the general case I don't think they are.  Apple's low latency HLS abandoned push fairly early on for that reason.

**Comment by DavidSchinazi** [comment]
Given that #52 has been merged, datagrams are now associated with request streams. That doesn't preclude push from using datagrams, because push is also associated with a request stream, but it does mean that datagrams are not directly linked to push streams.

**Comment by gloinul** [comment]
@DavidSchinazi maybe I am missing aspects of push, but I thought for push to work, you would have the push_promise frame from the server, which is not associated with a client HTTP request yet, and thus can't have HTTP Datagram. First when the client request the data that might be pushed will there be an actual HTTP request which could enable HTTP Datagram. 

Thus, from my perspective HTTP Push is not compatible with HTTP Datagram as currently defined. That is likely fine, but maybe these limitations should be clearly be noted.

**Comment by LPardue** [comment]
PUSH_PROMISE are always sent on request streams, they can only be issued by a server after a client has sent a request. The machinery across H2 and H3 is different for actually pushing but the promise aspect is similar. 

Server push is just weird and support for it is really poor across implementations. I am not in favour of spending effort on talking about server push when we don't support it by out design.

**Comment by gloinul** [comment]
@LPardue I have no interest in supporting Push. I think it comes down if one should note significant limitations in the specification?

**Comment by LPardue** [comment]
Since Server Push is the odd thing in HTTP land, I don't believe we need to give it any special mention. That's a pattern we follow in the HTTP WG.
