### ISSUE TITLE
How to actually use the Context ID registrations mechanism

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-h3-datagram#66]
Sent to the WG mailing list. 

I and my co-authors on https://datatracker.ietf.org/doc/draft-kuehlewind-masque-connect-ip/ have had some discussion around how one actually can and should be using the context-ID registration mechanism. This as we are actually need it to realize some of the functionality in our CONNECT-IP solution. 

We have found several ways that appear to practically work from an CONNECT-IP application perspective. 

A)	Statically define that in the context of CONNECT-IP the application will map certain formats to certain ContextID, and simply send registrations without any extension headers. 
B)	Define a Context Extension that is intended to provide format identifiers for the CONNECT-IP method different formats. 
C)	Use values or parameters in HTTP headers related to the format to carry the identifiers.
D)	Combine A and B, so that we have a set of initially statically defined mappings, and then use Context Extension for any future extensions. 

In our discussion we see that C appears to have some potential for failure modes if an HTTP intermediary does things with the headers. 

A) is very straight forward for an application initially but can run into trouble when needing to be extended but HTTP level negotiation of the general functionality should resolve those. 

B) appears to have some overhead from an application perspective as each application needs to define its own Context Extension to carry identifiers. Is it really intended that each HTTP application that needs to convey some identifier for its Context ID format to carry across the HTTP Datagram capsule. Would there be a point in defining a Context Extension that carries format identifier for what one like to use this context ID. 

D) appears to be simple initially, but leads to the extension mechanism having code paths that would not be exercised by default

So this was basically to start a discussion to see if we can get a bit more clearer guidance towards the HTTP application writers that will attempt to use HTTP Datagram on how to actually use Context IDs. I noted that the Connect-UDP method was no help as example yet.

**Comment by DavidSchinazi** [comment]
Thanks for writing this up @gloinul. Using your nomenclature, the draft is currently written with the intent of using (B). That allows maximal extensibility while ensuring that the extension codepath is well used. The overhead of registering a 62bit integer seems negligible to me - since each application needs to define its payload format somewhere, defining its negotiation format and registering an integer alongside seems easy. Can you think of any use cases that are not well served by (B)?

**Comment by gloinul** [comment]
Thanks for clarifying your thoughts on what you had intended. And I don't think there are any question if will serve the application. However, as there where no actually defined usage yet we where a bit uncertain of the intention here. 

I would note that each standardized application registering its own extension, will cause another IANA registry for the format values. But it clearly have a benefit from being a forensic perspective, as each application will be ID by its extension type, and then its value.

**Comment by DavidSchinazi** [comment]
Can you clarify your note? The document currently sets up the "HTTP Context Extension Types" IANA registry. What other IANA registry did you have in mind? Formats don't need a registry. To make an analogy, we have an IANA registry for UDP port numbers but no IANA registry for the format of UDP payloads, as those are defined by specifications not registries.

**Comment by gloinul** [comment]
So, lets take CONNECT-IP as an example. It will define and register a Context Extension Type for Connect-IP context IDs. 

In our current draft for Connect-IP we currently have 4 different formats that will need to be expressed by context ID registrations. We also have the ideas of at least one more to carry ECN. So the current specification will define what the first 4 values do. Then if we define the ECN one as a separate specification as additional extensions of CONNECT-IP formats. Thus we are in a situation where we need additional context-IDs identifiers, then the right thing to ensure that the format to value mapping is well managed is to create a new IANA registry for CONNECT-IP Context Extension Format to value mapping.

**Comment by DavidSchinazi** [comment]
I'm not sure I follow. You can have solve this by registering two Context Extension Types:
- one for the draft-kuehlewind-masque-connect-ip format which has the four values from that draft
- one for ECN which has four values Not-ECT/ECT(0)/ECT(1)/CE

and then you compose the results (by which I mean you can send multiple extensions in one REGISTER_DATAGRAM_CONTEXT capsule). I don't see how a separate registry helps?
