### ISSUE TITLE
Walkthrough of intended use

### ISSUE THREAD

**Issue by MikeBishop** [ietf-wg-masque/draft-ietf-masque-h3-datagram#79]
The document currently has a lot of tools, but there are different ways of thinking about how you could use them and why they're in the protocol.  I feel like readability would improve dramatically if the document started with an overview that described one or two hypothetical flows.

Not fully fleshed out protocols -- just an example of declaring a context associated to a request, request headers that inform the context, context extensions that inform it, exchanging datagrams, and closing the context.  The document makes reference to a few possible applications; maybe one of these could be drawn a little bit larger?

**Comment by LPardue** [comment]
For this request, what do you feel is missing from the examples in appendix A?

The reason I ask is that including those specific examples isn't great for the final version of this draft, the CONNECT-UDP spec is the canoncical source of the sequence and it depends on this document.

If there was a way to describe an example workflow in a more abstract sense, that addresses the gaps you're suggesting, then that would be a great candidate to keep in the document all the way through.

**Comment by MikeBishop** [comment]
Those are somewhat helpful, except that they're not referenced from the text.  Besides the cross-reference, the thing that's missing is a little bit of prose explaining why each element is sent at that point.  Are they identifying the protocol being used in that context?  Are they carrying configuration for that protocol?

The examples could perhaps be generalized by describing "an extension that carries supplemental metadata about the request," "an application carrying data referenced by the request," etc.
