### ISSUE TITLE
Consider splitting DATAGRAM Capsule into two types

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#81]
The DATAGRAM capsule has an optional Context ID field. The presence of this field is based on state held in stream objects, not signalled on the wire itself. 

IME it's rare that the parsing of an HTTP/3 frame (in this case, the CAPSULE frame that holds the capsule) is dependent on state in this way.

So the suggestion is to define DATAGRAM/DATAGRAM_NO_CONTEXT capsule types which would allow stateless parsing of frames. After a whole frame is read, receivers can then validate ordering rules such REGISTER_CONTEXT followed by DATAGRAM capsule, REGISTER_NO_CONTEXT followed by DATAGRAM_NO_CONTEXT.

This would also allow an early shortcut exit where the CAPSULE frame length can be used to validate that the DATAGRAM capsule is suitable large.

**Comment by LPardue** [comment]
Having now written the PR, I think the split also helps in the suggested drop / buffer case. Leaving the data in a stream isn't an option because it would block the later arriving register capsules, statelessly parsing the whole thing off the wire has a lot of attraction to me.

**Comment by LPardue** [comment]
aaand I completely overlooked that this also applies to the HTTP/3 datagram frame. I have similar concerns there.

**Comment by DavidSchinazi** [comment]
I find it pretty attractive to make parsing stateful, because it makes it harder for intermediaries to casually parse things they should not be parsing. When I implemented this last week, it required adding a bool to our HTTP/3 frames parser, which wasn't insurmountable. Since this stateful logic is required to parse QUIC DATAGRAM frames, I'd prefer the format of DATAGRAM capsules to closely match that of QUIC DATAGRAM frames.

**Comment by LPardue** [comment]
FWIW, the current design made it harder for me to parse the DATAGRAM capsule, which is explicitly defined as being transparent and malleable for intermediaries. 

On reflection though, this is about parsing frame payload not frame structure. I fell into the trap of putting this into my H3 frame parse code (sounds like maybe you did too?) when really this is equivalent trying to parse constructed header lists or content after extraction from DATA frames.

Much of where to write the code, and how to expose it to applications, is an implementation-specific choice.

**Comment by LPardue** [comment]
To add, I not convinced the proposed PR is required either but I'd appreciate some time to mull on this a bit more and play with implementation to understand if there is some other way to come a net improvement.

**Comment by DavidSchinazi** [comment]
Intermediaries do need to parse the datagram capsule type, but they don't need to parse the context ID nor payload, they just need to forward the "optional context ID followed by payload" opaque blob.

My implementation doesn't currently support acting as intermediary, so I have full parsing together for now. I plan on supporting this in Envoy as both intermediary and endpoint so I'll have to ponder how best to do that. I suspect I'll just split parsing in two: first half parses capsule type and opaque capsule data, second half parses capsule data according to the type.

But regardless, I totally agree that this is worth thinking about some more.

**Comment by LPardue** [comment]
Daivd said:
> Since this stateful logic is required to parse QUIC DATAGRAM frames, I'd prefer the format of DATAGRAM capsules to closely match that of QUIC DATAGRAM frames.

I'd overlooked this point earlier. There's not a cheap way to incorporate a CONTEXT/NO_CONTEXT discriminator into the HTTP/3 DATAGRAM frame. Spending a varint on that seems like a waste.

**Comment by DavidSchinazi** [comment]
@LPardue do you have further thoughts, or should we close this issue with no action?

**Comment by LPardue** [comment]
With the recent changes to the Capsule protocol definition I believe this
issue is mooted. Let's close it. But on grounds that I reserve the right to
reopen the issue should I find the same problem when implementing the new
design :-)

**Comment by DavidSchinazi** [comment]
You have the right to reopen any and all issues :-P
Closing based on discussion above.
