### ISSUE TITLE
Expand all capsule figures to include their Type and Length fields

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#94]
QUIC and HTTP/3 style is to define the general format and then in each instance define the object including all of its fields. This would look like

```
REGISTER_DATAGRAM_CONTEXT Capsule {
  Type (i) = see Section 8.2,
  Length (i)
  Context ID (i),
  Datagram Format Type (i),
  Datagram Format Additional Data (..),
}
```

This can later be updated with the actual type value once things settle down

**Comment by DavidSchinazi** [comment]
Fine by me.
